DROP TYPE IF EXISTS PALK_LIIB;
DROP TYPE IF EXISTS PALK_LIIK;

CREATE TYPE PALK_LIIK AS ENUM ('ARVESTUSED', 'KINNIPIDAMISED', 'MUUD', 'TULUMAKS', 'SOTSMAKS','TASU','TÖÖTUSKINDLUSTUSMAKS',
  'PENSIONIMAKS','ERISOODUS JA KINGITUSED');
