--DROP TYPE IF EXISTS PUUDUMISTE_LIIGID CASCADE ;

ALTER TYPE PUUDUMISTE_LIIGID ADD VALUE IF NOT EXISTS 'KOOLITUS' after 'MUU';

CREATE TYPE PUUDUMISTE_LIIGID AS ENUM ('PUHKUS', 'HAIGUS', 'KOMANDEERING', 'MUU','KOOLITUS');
