DROP TYPE IF EXISTS PALK_TUND_LIIK;

CREATE TYPE PALK_TUND_LIIK AS ENUM ('KÕIK', 'PÄEVAD', 'ÕHTUL', 'ÖÖSEL', 'PUHKUS');

ALTER TYPE PALK_TUND_LIIK
ADD VALUE 'PÜHAPAEVAL';

ALTER TYPE PALK_TUND_LIIK
ADD VALUE 'ÜLEAJATÖÖ';

ALTER TYPE PALK_TUND_LIIK
ADD VALUE 'HAIGUS';

--'ÜLEAJATÖÖ','HAIGUS'