module.exports = {
    dok:'dok',
    arv:'/lapsed/arv',
    smk:'/lapsed/smk',
    vmk:'/lapsed/vmk',
    journal:'/lapsed/journal',
    sorder:'/lapsed/sorder',
    vorder:'/lapsed/vorder',
    asutused:'/libs/libraries/asutused',
    kontod:'/libs/libraries/kontod',
    dokprops: '/libs/libraries/dokprops',
    userid: '/ou/userid',
    users: '/ou/userid',
    rekv:'/ou/rekv',
    nomenclature: '/lapsed/nomenclature',
    document: '/libs/libraries/document',
    aa: '/ou/aa',
    kassa: '/ou/kassa',
    tunnus: '/libs/libraries/tunnus',
    project: '/libs/libraries/project',
    artikkel:'/libs/libraries/artikkel',
    allikas:'/libs/libraries/allikas',
    tegev:'/libs/libraries/tegev',
    laps:'/lapsed/laps',
    vanem:'/lapsed/vanem',
    lapse_kaart:'/lapsed/lapse_kaart',
    lapse_taabel:'/lapsed/lapse_taabel',
    paeva_taabel: '/lapsed/paeva_taabel',
    lapse_grupp:'/lapsed/lapse_grupp',
    pank_vv: '/lapsed/pank_vv',
    config: '/ou/config',
    inf3:'/aruanned/lapsed/inf3',
    laps_kokkuvotte:'/aruanned/lapsed/laps_kokkuvotte',
    arved_koodi_jargi:'/aruanned/lapsed/arved_koodi_jargi',
    saldo_ja_kaive:'/aruanned/lapsed/saldo_ja_kaive',
    sent_docs:'/aruanned/lapsed/sent_docs',
    child_age:'/aruanned/lapsed/child_age',
    soodustused: '/aruanned/lapsed/soodustused',
    statistika: '/aruanned/lapsed/statistika',
    ebatoenaolised: '/aruanned/lapsed/ebatoenaolised',
    kondarve: '/aruanned/lapsed/kondarve',
    aasta_naitajad: '/aruanned/lapsed/aasta_naitajad',
    teatis: '/lapsed/teatis',
    asutuse_liik: '/libs/libraries/asutuse_liik',
    koolituse_tyyp: '/libs/libraries/koolituse_tyyp',
    koolituse_liik: '/libs/libraries/koolituse_liik',
    kuu_taabel: '/aruanned/lapsed/kuu_taabel',
    yksuse_taabel: '/aruanned/lapsed/yksuse_taabel',
    kohaloleku_aruanne: '/aruanned/lapsed/kohaloleku_aruanne',
};