module.exports = {
    dok:'dok',
    arv:'/lapsed/arv',
    smk:'/lapsed/smk',
    vmk:'/lapsed/vmk',
    journal:'/lapsed/journal',
    sorder:'/lapsed/sorder',
    vorder:'/lapsed/vorder',
    asutused:'/libs/libraries/asutused',
    kontod:'/libs/libraries/kontod',
    dokprops: '/libs/libraries/dokprops',
    users: '/ou/userid',
    nomenclature: '/libs/libraries/nomenclature',
    document: '/libs/libraries/document',
    aa: '/ou/aa',
    kassa: '/ou/kassa',
    tunnus: '/libs/libraries/tunnus',
    project: '/libs/libraries/project',
    artikkel:'/libs/libraries/artikkel',
    allikas:'/libs/libraries/allikas',
    tegev:'/libs/libraries/tegev',
    laps:'/lapsed/laps',
    vanem:'/lapsed/vanem',
    lapse_kaart:'/lapsed/lapse_kaart',
    lapse_taabel:'/lapsed/lapse_taabel'
};