module.exports = {
    grid: {
        gridConfiguration: [
            {id: "yksus", name: "Üksus", width: "7%"},
            {id: "viitenr", name: "Viitenr.", width: "7%"},
            {id: "nimi", name: "Nimi", width: "8%"},
            {id: "teenus", name: "Teenus", width: "5%"},
            {id: "kuu", name: "Kuu", width: "3%", type: "integer"},
            {id: "aasta", name: "Aasta", width: "4%", type: "integer"},
            {
                id: "day_1",
                name: "1",
                width: "2%",
                hideFilter: true,
                type: "boolean",
                boolSumbolYes: 1,
                boolSumbolNo: '0',
                boolSumbolNull: ' '
            },
            {
                id: "day_2",
                name: "2",
                width: "2%",
                hideFilter: true,
                type: "boolean",
                boolSumbolYes: 1,
                boolSumbolNo: '0',
                boolSumbolNull: ' '
            },
            {
                id: "day_3",
                name: "3",
                width: "2%",
                hideFilter: true,
                type: "boolean",
                boolSumbolYes: 1,
                boolSumbolNo: '0',
                boolSumbolNull: ' '
            },
            {
                id: "day_4",
                name: "4",
                width: "2%",
                hideFilter: true,
                type: "boolean",
                boolSumbolYes: 1,
                boolSumbolNo: '0',
                boolSumbolNull: ' '
            },
            {
                id: "day_5",
                name: "5",
                width: "2%",
                hideFilter: true,
                type: "boolean",
                boolSumbolYes: 1,
                boolSumbolNo: '0',
                boolSumbolNull: ' '
            },
            {
                id: "day_6",
                name: "6",
                width: "2%",
                hideFilter: true,
                type: "boolean",
                boolSumbolYes: 1,
                boolSumbolNo: '0',
                boolSumbolNull: ' '
            },
            {
                id: "day_7",
                name: "7",
                width: "2%",
                hideFilter: true,
                type: "boolean",
                boolSumbolYes: 1,
                boolSumbolNo: '0',
                boolSumbolNull: ' '
            },
            {
                id: "day_8",
                name: "8",
                width: "2%",
                hideFilter: true,
                type: "boolean",
                boolSumbolYes: 1,
                boolSumbolNo: '0',
                boolSumbolNull: ' '
            },
            {
                id: "day_9",
                name: "9",
                width: "2%",
                hideFilter: true,
                type: "boolean",
                boolSumbolYes: 1,
                boolSumbolNo: '0',
                boolSumbolNull: ' '
            },
            {
                id: "day_10",
                name: "10",
                width: "2%",
                hideFilter: true,
                type: "boolean",
                boolSumbolYes: 1,
                boolSumbolNo: '0',
                boolSumbolNull: ' '
            },
            {
                id: "day_11",
                name: "11",
                width: "2%",
                hideFilter: true,
                type: "boolean",
                boolSumbolYes: 1,
                boolSumbolNo: '0',
                boolSumbolNull: ' '
            },
            {
                id: "day_12",
                name: "12",
                width: "2%",
                hideFilter: true,
                type: "boolean",
                boolSumbolYes: 1,
                boolSumbolNo: '0',
                boolSumbolNull: ' '
            },
            {
                id: "day_13",
                name: "13",
                width: "2%",
                hideFilter: true,
                type: "boolean",
                boolSumbolYes: 1,
                boolSumbolNo: '0',
                boolSumbolNull: ' '
            },
            {
                id: "day_14",
                name: "14",
                width: "2%",
                hideFilter: true,
                type: "boolean",
                boolSumbolYes: 1,
                boolSumbolNo: '0',
                boolSumbolNull: ' '
            },
            {
                id: "day_15",
                name: "15",
                width: "2%",
                hideFilter: true,
                type: "boolean",
                boolSumbolYes: 1,
                boolSumbolNo: '0',
                boolSumbolNull: ' '
            },
            {
                id: "day_16",
                name: "16",
                width: "2%",
                hideFilter: true,
                type: "boolean",
                boolSumbolYes: 1,
                boolSumbolNo: '0',
                boolSumbolNull: ' '
            },
            {
                id: "day_17",
                name: "17",
                width: "2%",
                hideFilter: true,
                type: "boolean",
                boolSumbolYes: 1,
                boolSumbolNo: '0',
                boolSumbolNull: ' '
            },
            {
                id: "day_18",
                name: "18",
                width: "2%",
                hideFilter: true,
                type: "boolean",
                boolSumbolYes: 1,
                boolSumbolNo: '0',
                boolSumbolNull: ' '
            },
            {
                id: "day_19",
                name: "19",
                width: "2%",
                hideFilter: true,
                type: "boolean",
                boolSumbolYes: 1,
                boolSumbolNo: '0',
                boolSumbolNull: ' '
            },
            {
                id: "day_20",
                name: "20",
                width: "2%",
                hideFilter: true,
                type: "boolean",
                boolSumbolYes: 1,
                boolSumbolNo: '0',
                boolSumbolNull: ' '
            },
            {
                id: "day_21",
                name: "21",
                width: "2%",
                hideFilter: true,
                type: "boolean",
                boolSumbolYes: 1,
                boolSumbolNo: '0',
                boolSumbolNull: ' '
            },
            {
                id: "day_22",
                name: "22",
                width: "2%",
                hideFilter: true,
                type: "boolean",
                boolSumbolYes: 1,
                boolSumbolNo: '0',
                boolSumbolNull: ' '
            },
            {
                id: "day_23",
                name: "23",
                width: "2%",
                hideFilter: true,
                type: "boolean",
                boolSumbolYes: 1,
                boolSumbolNo: '0',
                boolSumbolNull: ' '
            },
            {
                id: "day_24",
                name: "24",
                width: "2%",
                hideFilter: true,
                type: "boolean",
                boolSumbolYes: 1,
                boolSumbolNo: '0',
                boolSumbolNull: ' '
            },
            {
                id: "day_25",
                name: "25",
                width: "2%",
                hideFilter: true,
                type: "boolean",
                boolSumbolYes: 1,
                boolSumbolNo: '0',
                boolSumbolNull: ' '
            },
            {
                id: "day_26",
                name: "26",
                width: "2%",
                hideFilter: true,
                type: "boolean",
                boolSumbolYes: 1,
                boolSumbolNo: '0',
                boolSumbolNull: ' '
            },
            {
                id: "day_27",
                name: "27",
                width: "2%",
                hideFilter: true,
                type: "boolean",
                boolSumbolYes: 1,
                boolSumbolNo: '0',
                boolSumbolNull: ' '
            },
            {
                id: "day_28",
                name: "28",
                width: "2%",
                hideFilter: true,
                type: "boolean",
                boolSumbolYes: 1,
                boolSumbolNo: '0',
                boolSumbolNull: ' '
            },
            {
                id: "day_29",
                name: "29",
                width: "2%",
                hideFilter: true,
                type: "boolean",
                boolSumbolYes: 1,
                boolSumbolNo: '0',
                boolSumbolNull: ' '
            },
            {
                id: "day_30",
                name: "30",
                width: "2%",
                hideFilter: true,
                type: "boolean",
                boolSumbolYes: 1,
                boolSumbolNo: '0',
                boolSumbolNull: ' '
            },
            {
                id: "day_31",
                name: "31",
                width: "2%",
                hideFilter: true,
                type: "boolean",
                boolSumbolYes: 1,
                boolSumbolNo: '0',
                boolSumbolNull: ' '
            },
            {id: "kogus", name: "kokku", width: "2%", hideFilter: true, type: "integer"}
//            {id: "tuhi", name: " ", width: "1px", hideFilter: true},
        ],
        sqlString: `SELECT yksus,
                           nom_id,
                           teenus,
                           isikukood,
                           viitenr,
                           nimi,
                           kuu,
                           aasta,
                           kogus,
                           day_1,
                           day_2,
                           day_3,
                           day_4,
                           day_5,
                           day_6,
                           day_7,
                           day_8,
                           day_9,
                           day_10,
                           day_11,
                           day_12,
                           day_13,
                           day_14,
                           day_15,
                           day_16,
                           day_17,
                           day_18,
                           day_19,
                           day_20,
                           day_21,
                           day_22,
                           day_23,
                           day_24,
                           day_25,
                           day_26,
                           day_27,
                           day_28,
                           day_29,
                           day_30,
                           day_31,
                           (day_1 + day_2 + day_3 + day_4 + day_5 + day_6 + day_7 + day_8 + day_9 + day_10 + day_11 +
                            day_12
                               + day_13 + day_14 + day_15 + day_16 + day_17 + day_18 + day_19 + day_20 + day_21 + day_22
                               + day_23 + day_24 + day_25 + day_26 + day_27 + day_28 + day_29 + day_30 +
                            day_31)::INTEGER                     AS kuu_kokku,
                           sum(day_1) OVER (PARTITION BY yksus)  AS total_1,
                           sum(day_2) OVER (PARTITION BY yksus)  AS total_2,
                           sum(day_3) OVER (PARTITION BY yksus)  AS total_3,
                           sum(day_4) OVER (PARTITION BY yksus)  AS total_4,
                           sum(day_5) OVER (PARTITION BY yksus)  AS total_5,
                           sum(day_6) OVER (PARTITION BY yksus)  AS total_6,
                           sum(day_7) OVER (PARTITION BY yksus)  AS total_7,
                           sum(day_8) OVER (PARTITION BY yksus)  AS total_8,
                           sum(day_9) OVER (PARTITION BY yksus)  AS total_9,
                           sum(day_10) OVER (PARTITION BY yksus) AS total_10,
                           sum(day_11) OVER (PARTITION BY yksus) AS total_11,
                           sum(day_12) OVER (PARTITION BY yksus) AS total_12,
                           sum(day_13) OVER (PARTITION BY yksus) AS total_13,
                           sum(day_14) OVER (PARTITION BY yksus) AS total_14,
                           sum(day_15) OVER (PARTITION BY yksus) AS total_15,
                           sum(day_16) OVER (PARTITION BY yksus) AS total_16,
                           sum(day_17) OVER (PARTITION BY yksus) AS total_17,
                           sum(day_18) OVER (PARTITION BY yksus) AS total_18,
                           sum(day_19) OVER (PARTITION BY yksus) AS total_19,
                           sum(day_20) OVER (PARTITION BY yksus) AS total_20,
                           sum(day_21) OVER (PARTITION BY yksus) AS total_21,
                           sum(day_22) OVER (PARTITION BY yksus) AS total_22,
                           sum(day_23) OVER (PARTITION BY yksus) AS total_23,
                           sum(day_24) OVER (PARTITION BY yksus) AS total_24,
                           sum(day_25) OVER (PARTITION BY yksus) AS total_25,
                           sum(day_26) OVER (PARTITION BY yksus) AS total_26,
                           sum(day_27) OVER (PARTITION BY yksus) AS total_27,
                           sum(day_28) OVER (PARTITION BY yksus) AS total_28,
                           sum(day_29) OVER (PARTITION BY yksus) AS total_29,
                           sum(day_30) OVER (PARTITION BY yksus) AS total_30,
                           sum(day_31) OVER (PARTITION BY yksus) AS total_31,
                           week_ends::INTEGER[]                  AS week_ends,
                           men_count::INTEGER
                    FROM lapsed.yksuse_taabel($1::INTEGER, $2::INTEGER, $3::INTEGER) qryReport
                    ORDER BY yksus, nimi, nom_id DESC
        `,     // $1 - rekvid, $2-KUU $3 - aasta
        params: ['rekvid', 'kuu', 'aasta'],
        alias: 'yksuse_taabel_report',
        subtotals: ['day_1', 'day_2', 'day_3', 'day_4', 'day_5', 'day_6', 'day_7', 'day_8', 'day_9', 'day_10', 'day_11', 'day_12', 'day_13', 'day_14', 'day_15', 'day_16', 'day_17', 'day_18', 'day_19', 'day_20', 'day_21', 'day_22', 'day_23', 'day_24', 'day_25', 'day_26', 'day_27', 'day_28', 'day_29', 'day_30', 'day_31']
    },
    print: [
        {
            view: 'yksuse_taabel_register',
            params: 'sqlWhere',
            group: 'yksus'

        },
    ],

};
