module.exports = {
    grid: {
        gridConfiguration: [
            {id: "yksus", name: "Üksus", width: "7%"},
            {id: "viitenr", name: "Viitenr.", width: "7%"},
            {id: "nimi", name: "Nimi", width: "8%"},
            {id: "teenus", name: "Teenus", width: "5%"},
            {id: "kuu", name: "Kuu", width: "3%", type: "integer"},
            {id: "aasta", name: "Aasta", width: "4%", type: "integer"},
            {
                id: "day_1",
                name: "1",
                width: "2%",
                hideFilter: true,
            },
            {
                id: "day_2",
                name: "2",
                width: "2%",
                hideFilter: true,
            },
            {
                id: "day_3",
                name: "3",
                width: "2%",
                hideFilter: true,
            },
            {
                id: "day_4",
                name: "4",
                width: "2%",
                hideFilter: true,
            },
            {
                id: "day_5",
                name: "5",
                width: "2%",
                hideFilter: true,
            },
            {
                id: "day_6",
                name: "6",
                width: "2%",
                hideFilter: true,
            },
            {
                id: "day_7",
                name: "7",
                width: "2%",
                hideFilter: true,
            },
            {
                id: "day_8",
                name: "8",
                width: "2%",
                hideFilter: true,
            },
            {
                id: "day_9",
                name: "9",
                width: "2%",
                hideFilter: true,
            },
            {
                id: "day_10",
                name: "10",
                width: "2%",
                hideFilter: true,
            },
            {
                id: "day_11",
                name: "11",
                width: "2%",
                hideFilter: true,
            },
            {
                id: "day_12",
                name: "12",
                width: "2%",
                hideFilter: true,
            },
            {
                id: "day_13",
                name: "13",
                width: "2%",
                hideFilter: true,
            },
            {
                id: "day_14",
                name: "14",
                width: "2%",
                hideFilter: true,
            },
            {
                id: "day_15",
                name: "15",
                width: "2%",
                hideFilter: true,
            },
            {
                id: "day_16",
                name: "16",
                width: "2%",
                hideFilter: true,
            },
            {
                id: "day_17",
                name: "17",
                width: "2%",
                hideFilter: true,
            },
            {
                id: "day_18",
                name: "18",
                width: "2%",
                hideFilter: true,
            },
            {
                id: "day_19",
                name: "19",
                width: "2%",
                hideFilter: true,
            },
            {
                id: "day_20",
                name: "20",
                width: "2%",
                hideFilter: true,
            },
            {
                id: "day_21",
                name: "21",
                width: "2%",
                hideFilter: true,
            },
            {
                id: "day_22",
                name: "22",
                width: "2%",
                hideFilter: true,
            },
            {
                id: "day_23",
                name: "23",
                width: "2%",
                hideFilter: true,
            },
            {
                id: "day_24",
                name: "24",
                width: "2%",
                hideFilter: true,
            },
            {
                id: "day_25",
                name: "25",
                width: "2%",
                hideFilter: true,
            },
            {
                id: "day_26",
                name: "26",
                width: "2%",
                hideFilter: true,
            },
            {
                id: "day_27",
                name: "27",
                width: "2%",
                hideFilter: true,
            },
            {
                id: "day_28",
                name: "28",
                width: "2%",
                hideFilter: true,
            },
            {
                id: "day_29",
                name: "29",
                width: "2%",
                hideFilter: true,
            },
            {
                id: "day_30",
                name: "30",
                width: "2%",
                hideFilter: true,
            },
            {
                id: "day_31",
                name: "31",
                width: "2%",
                hideFilter: true,
            },
            {id: "kogus", name: "kokku", width: "2%", hideFilter: true, type: "integer"}
//            {id: "tuhi", name: " ", width: "1px", hideFilter: true},
        ],
        sqlString: `
            SELECT *
            FROM (
                     SELECT row_number() OVER (PARTITION BY yksus, isikukood 
                         ORDER BY
                         yksus,
                         nimi,
                         isikukood,                         
                         nom_id DESC
                         ,is_row)     AS rea_count,
                            *
                     FROM (
                              WITH yksuse_taabel AS (
                                  SELECT yksus,
                                         nom_id,
                                         teenus,
                                         isikukood,
                                         viitenr,
                                         nimi,
                                         kuu,
                                         aasta,
                                         kogus,
                                         case WHEN nom_id <> 999999999 and day_1 = 0 THEN null else day_1 end as day_1,
                                         case WHEN  nom_id <> 999999999 and day_2 = 0 THEN null else day_2 end as day_2,
                                         case WHEN  nom_id <> 999999999 and day_3 = 0 THEN null else day_3 end as day_3,
                                         case WHEN  nom_id <> 999999999 and day_4 = 0 THEN null else day_4 end as day_4,
                                         case WHEN  nom_id <> 999999999 and day_5 = 0 THEN null else day_5 end as day_5,
                                         case WHEN  nom_id <> 999999999 and day_6 = 0 THEN null else day_6 end as day_6,
                                         case WHEN  nom_id <> 999999999 and day_7 = 0 THEN null else day_7 end as day_7,
                                         case WHEN  nom_id <> 999999999 and day_8 = 0 THEN null else day_8 end as day_8,
                                         case WHEN  nom_id <> 999999999 and day_9 = 0 THEN null else day_9 end as day_9,
                                         case WHEN  nom_id <> 999999999 and day_10 = 0 THEN null else day_10 end as day_10,
                                         case WHEN  nom_id <> 999999999 and day_11 = 0 THEN null else day_11 end as day_11,
                                         case WHEN  nom_id <> 999999999 and day_12 = 0 THEN null else day_12 end as day_12,
                                         case WHEN  nom_id <> 999999999 and day_13 = 0 THEN null else day_13 end as day_13,
                                         case WHEN  nom_id <> 999999999 and day_14 = 0 THEN null else day_14 end as day_14,
                                         case WHEN  nom_id <> 999999999 and day_15 = 0 THEN null else day_15 end as day_15,
                                         case WHEN  nom_id <> 999999999 and day_16 = 0 THEN null else day_16 end as day_16,
                                         case WHEN  nom_id <> 999999999 and day_17 = 0 THEN null else day_17 end as day_17,
                                         case WHEN  nom_id <> 999999999 and day_18 = 0 THEN null else day_18 end as day_18,
                                         case WHEN  nom_id <> 999999999 and day_19 = 0 THEN null else day_19 end as day_19,
                                         case WHEN  nom_id <> 999999999 and day_20 = 0 THEN null else day_20 end as day_20,
                                         case WHEN  nom_id <> 999999999 and day_21 = 0 THEN null else day_21 end as day_21,
                                         case WHEN  nom_id <> 999999999 and day_22 = 0 THEN null else day_22 end as day_22,
                                         case WHEN  nom_id <> 999999999 and day_23 = 0 THEN null else day_23 end as day_23,
                                         case WHEN  nom_id <> 999999999 and day_24 = 0 THEN null else day_24 end as day_24,
                                         case WHEN  nom_id <> 999999999 and day_25 = 0 THEN null else day_25 end as day_25,
                                         case WHEN  nom_id <> 999999999 and day_26 = 0 THEN null else day_26 end as day_26,
                                         case WHEN  nom_id <> 999999999 and day_27 = 0 THEN null else day_27 end as day_27,
                                         case WHEN  nom_id <> 999999999 and day_28 = 0 THEN null else day_28 end as day_28,
                                         case WHEN  nom_id <> 999999999 and day_29 = 0 THEN null else day_29 end as day_29,
                                         case WHEN  nom_id <> 999999999 and day_30 = 0 THEN null else day_30 end as day_30,
                                         case WHEN  nom_id <> 999999999 and day_31 = 0 THEN null else day_31 end as day_31,
                                         week_ends::INTEGER[] AS week_ends
                                  FROM lapsed.yksuse_taabel($1::INTEGER, $2::INTEGER, $3::INTEGER) qryReport
                                      ORDER BY
                                       yksus,
                                       nimi,
                                       nom_id DESC
                              )
                              SELECT TRUE AS is_row,
                                     CASE WHEN nom_id = 999999999 THEN TRUE ELSE FALSE END AS is_osa,
                                     *
                              FROM yksuse_taabel
                                  UNION ALL
                                  SELECT
                                   FALSE AS is_row,
                                   CASE WHEN nom_id = 999999999 THEN TRUE ELSE FALSE END AS is_osa,
                                   yksus,
                                   nom_id,
                                   teenus,
                                   'XXXXXXXXXXX',
                                   'XXXXXXXXXXX',
                                   'Kokku' AS nimi,
                                   kuu,
                                   aasta,
                                   sum(kogus) AS kogus,
                                   sum(day_1) AS day_1,
                                   sum(day_2) AS day_2,
                                   sum(day_3) AS day_3,
                                   sum(day_4) AS day_4,
                                   sum(day_5) AS day_5,
                                   sum(day_6) AS day_6,
                                   sum(day_7) AS day_7,
                                   sum(day_8) AS day_8,
                                   sum(day_9) AS day_9,
                                   sum(day_10) AS day_10,
                                   sum(day_11) AS day_11,
                                   sum(day_12) AS day_12,
                                   sum(day_13) AS day_13,
                                   sum(day_14) AS day_14,
                                   sum(day_15) AS day_15,
                                   sum(day_16) AS day_16,
                                   sum(day_17) AS day_17,
                                   sum(day_18) AS day_18,
                                   sum(day_19) AS day_19,
                                   sum(day_20) AS day_20,
                                   sum(day_21) AS day_21,
                                   sum(day_22) AS day_22,
                                   sum(day_23) AS day_23,
                                   sum(day_24) AS day_24,
                                   sum(day_25) AS day_25,
                                   sum(day_26) AS day_26,
                                   sum(day_27) AS day_27,
                                   sum(day_28) AS day_28,
                                   sum(day_29) AS day_29,
                                   sum(day_30) AS day_30,
                                   sum(day_31) AS day_31,
                                   NULL::INTEGER[] AS week_ends
                                  FROM
                                   yksuse_taabel
                                  GROUP BY
                                   yksus,
                                   nom_id,
                                   teenus,
                                   kuu,
                                   aasta
                                  UNION ALL
                                  SELECT
                                   FALSE AS is_row,
                                   FALSE AS is_osa,
                                   yksus,
                                   1,
                                   'Kalendripäevad kokku',
                                   'XXXXXXXXXXX',
                                   'XXXXXXXXXXX',
                                   'Kokku' AS nimi,
                                   kuu,
                                   aasta,
                                   day(gomonth(make_date($3,$2,01),1) - 1) AS kogus,
                                   NULL AS day_1,
                                   NULL AS day_2,
                                   NULL AS day_3,
                                   NULL AS day_4,
                                   NULL AS day_5,
                                   NULL AS day_6,
                                   NULL AS day_7,
                                   NULL AS day_8,
                                   NULL AS day_9,
                                   NULL AS day_10,
                                   NULL AS day_11,
                                   NULL AS day_12,
                                   NULL AS day_13,
                                   NULL AS day_14,
                                   NULL AS day_15,
                                   NULL AS day_16,
                                   NULL AS day_17,
                                   NULL AS day_18,
                                   NULL AS day_19,
                                   NULL AS day_20,
                                   NULL AS day_21,
                                   NULL AS day_22,
                                   NULL AS day_23,
                                   NULL AS day_24,
                                   NULL AS day_25,
                                   NULL AS day_26,
                                   NULL AS day_27,
                                   NULL AS day_28,
                                   NULL AS day_29,
                                   NULL AS day_30,
                                   NULL AS day_31,
                                   NULL::INTEGER[] AS week_ends
                                  FROM
                                   yksuse_taabel
                                  GROUP BY
                                   yksus,
                                   kuu,
                                   aasta
                                  UNION ALL
                                   -- toopaevad
                                  SELECT
                                   FALSE AS is_row,
                                   FALSE AS is_osa,
                                   yksus,
                                   2,
                                   'Tööpäevad kokku',
                                   'XXXXXXXXXXX',
                                   'XXXXXXXXXXX',
                                   'Kokku' AS nimi,
                                   kuu,
                                   aasta,
                                   palk.get_work_days((SELECT row_to_json(row)
                                                       FROM (SELECT $2    AS kuu,
                                                                    $3 AS aasta,
                                                                    $1   AS rekvid) row))
                                       AS kogus,
                                   NULL AS day_1,
                                   NULL AS day_2,
                                   NULL AS day_3,
                                   NULL AS day_4,
                                   NULL AS day_5,
                                   NULL AS day_6,
                                   NULL AS day_7,
                                   NULL AS day_8,
                                   NULL AS day_9,
                                   NULL AS day_10,
                                   NULL AS day_11,
                                   NULL AS day_12,
                                   NULL AS day_13,
                                   NULL AS day_14,
                                   NULL AS day_15,
                                   NULL AS day_16,
                                   NULL AS day_17,
                                   NULL AS day_18,
                                   NULL AS day_19,
                                   NULL AS day_20,
                                   NULL AS day_21,
                                   NULL AS day_22,
                                   NULL AS day_23,
                                   NULL AS day_24,
                                   NULL AS day_25,
                                   NULL AS day_26,
                                   NULL AS day_27,
                                   NULL AS day_28,
                                   NULL AS day_29,
                                   NULL AS day_30,
                                   NULL AS day_31,
                                   NULL::INTEGER[] AS week_ends
                                  FROM
                                   yksuse_taabel
                                  GROUP BY
                                   yksus,
                                   kuu,
                                   aasta
                         
                          ) qry
                 ) qry
                ORDER BY
                 yksus,
                 is_row desc,
                 nimi,
                 is_osa DESC, teenus`,     // $1 - rekvid, $2-KUU $3 - aasta
        params: ['rekvid', 'kuu', 'aasta'],
        alias: 'yksuse_taabel_report',
        subtotals: ['day_1', 'day_2', 'day_3', 'day_4', 'day_5', 'day_6', 'day_7', 'day_8', 'day_9', 'day_10', 'day_11', 'day_12', 'day_13', 'day_14', 'day_15', 'day_16', 'day_17', 'day_18', 'day_19', 'day_20', 'day_21', 'day_22', 'day_23', 'day_24', 'day_25', 'day_26', 'day_27', 'day_28', 'day_29', 'day_30', 'day_31']
    },
    print: [
        {
            view: 'yksuse_taabel_register',
            params: 'sqlWhere',
            group: 'yksus'

        },
    ],

};
